### ISSUE TITLE
Update to use NetworkCallback

### ISSUE THREAD

**Issue by mrclayman** [googlesamples/android-BasicNetworking#1]
Hi, since the `NetworkInfo` type has been deprecated in the newer versions of Android, would it be possible for this example to get updated to use the new `NetworkCallback` approach, especially as it relates to how to use network connection on on-demand basis? To me, the callback approach looks like it's meant to keep track of the network state on my end rather than just querying the current state whenever necessary. Thanks. :slightly_smiling_face:

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
